/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type {ColumnType} from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ActivityLogs {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  moduleId: string;
  performerId: string;
  title: string;
}

export interface ModulePermissions {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  moduleId: string;
  permissionId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Modules {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Permissions {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface RolePermissions {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  modulePermissionId: string;
  roleId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Roles {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  expiresAt: Timestamp;
  id: Generated<string>;
  lastLogin: Timestamp | null;
  refreshToken: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface UserRoles {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  roleId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  email: string;
  firstName: string;
  id: Generated<string>;
  lastName: string;
  password: string;
  profilePhoto: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  ActivityLogs: ActivityLogs;
  ModulePermissions: ModulePermissions;
  Modules: Modules;
  Permissions: Permissions;
  RolePermissions: RolePermissions;
  Roles: Roles;
  Sessions: Sessions;
  UserRoles: UserRoles;
  Users: Users;
}
